from flask import Flask, request, jsonify
from flask_cors import CORS
import requests
import os

app = Flask(__name__)

# Enable CORS only for your frontend origin
CORS(app, resources={r"/generate-quiz": {"origins": "http://localhost:5173"}})

# Load the Gemini API key from environment variable or fallback (for development)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "AIzaSyD1Cv2q5NYCv42-VvyDYjdsMt1eDQIRy0I")

@app.route('/')
def home():
    return 'Flask backend is running!'

@app.route('/generate-quiz', methods=['POST'])
def generate_quiz():
    data = request.json
    language = data.get('language', 'Python')
    level = data.get('level', 'easy')

    prompt = (
        f"Generate 5 {level} level multiple-choice questions for {language}. "
        "Each question should have 4 options (A to D) and clearly mention the correct answer."
    )

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}

    try:
        response = requests.post(url, json={
            "contents": [{"parts": [{"text": prompt}]}]
        }, headers=headers)

        if response.status_code != 200:
            return jsonify({"error": "Gemini API call failed", "details": response.json()}), response.status_code

        result = response.json()
        print("Gemini API response:", result)

        # Safely extract quiz content
        candidates = result.get("candidates", [])
        if not candidates:
            return jsonify({"content": "No quiz generated by Gemini."})

        parts = candidates[0].get("content", {}).get("parts", [])
        if not parts:
            return jsonify({"content": "No quiz content returned by Gemini."})

        text = parts[0].get("text", "No text found.")
        return jsonify({"content": text})

    except Exception as e:
        return jsonify({"error": "Server error", "details": str(e)}), 500


if __name__ == '__main__':
    app.run(debug=True)
